name: ML Pipeline Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily schedule for retrain-deploy workflow

jobs:
  install-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Python version
        run: python3 --version

      - name: Check Pip version
        run: pip3 --version

      - name: Create .env file containing secrets
        run: |
          cat <<- EOF .env
          DEPLOY_SERVER_HOSTNAME=${{ secrets.DEPLOY_SERVER_HOSTNAME }}
          DEPLOY_SERVER_USERNAME=${{ secrets.DEPLOY_SERVER_USERNAME }}
          DEPLOY_SERVER_PASSWORD=${{ secrets.DEPLOY_SERVER_PASSWORD }}
          DEPLOY_SERVER_PATH=${{ secrets.DEPLOY_SERVER_PATH }}
          EOF

      - name: Run script to install dependencies
        run: source ./abilities/install.sh

      - name: Build the model
        run: source ./venv/bin/activate && python3 ./ml/1_build.py

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: |
            venv
            ml
            .env
            abilities

  train:
    runs-on: self-hosted
    needs: install-build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Train the model
        run: source ./venv/bin/activate && python3 ./ml/2_train.py

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ml

  test:
    runs-on: self-hosted
    needs: train
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Test the model
        run: source ./venv/bin/activate && python3 ./ml/3_test.py

  retrain:
    runs-on: self-hosted
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Retrain the model
        run: source ./venv/bin/activate && python3 ./ml/6_retrain.py

      - name: Run on fail status
        if: failure()
        run: echo "I am the result of the above failed job"

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ml

  package:
    runs-on: self-hosted
    needs: [test, retrain]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Package the model
        run: source ./venv/bin/activate && python3 ./ml/4_package.py

  deploy:
    runs-on: self-hosted
    needs: package
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Deploy the model
        run: source ./venv/bin/activate && python3 ./ml/5_deploy.py

  test-deployment:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Wait 5 seconds
        run: sleep 5

      - name: Test the deployed model
        run: source ./venv/bin/activate && python3 ./ml/7_test_deployed_model.py